### PR TITLE
Extract all public stuff from `dfuzzer.h` and drop the file completely

### PR DESCRIPTION
**Pull request by mrc0mmand**
This way we should be able to link against all fuzz/rand related dfuzzer stuff in future unit tests.

Note: this is currently based on top of #115, since I want to see how CI is going to like it.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Oh well, I guess no CI for me https://www.githubstatus.com/incidents/qzmhbwp7f6nn :-)

**Comment by evverx** [comment]
The first two commits look good to me (though I'm not sure `df_fuzz_set_buffer_length` should be the only place where `fuzz_buffer_length` is checked). I think in addition to the assertion it should be verified somewhere along with `buf_length < MIN_BUFFER_LENGTH` with a clear warning/error.

The last commit is kind of controversial. I think ideally the suppression part should go to a separate file to make it easier to test it with unit tests of some kind.

**Comment by mrc0mmand** [comment]
> The first two commits look good to me (though I'm not sure `df_fuzz_set_buffer_length` should be the only place where `fuzz_buffer_length` is checked). I think in addition to the assertion it should be verified somewhere along with `buf_length < MIN_BUFFER_LENGTH` with a clear warning/error.

Whoops, I though we already check both MIN a MAX_BUFFER_LENGTH, will fix.

> 
> The last commit is kind of controversial. I think ideally the suppression part should go to a separate file to make it easier to test it with unit tests of some kind.

That's a good point, let me fix that.

**Comment by mrc0mmand** [comment]
Note for future RFE: we should probably check the CI logs somehow for sanitizer errors (or change the exit code & check for it), since I almost missed https://github.com/dbus-fuzzer/dfuzzer/runs/7171253508?check_suite_focus=true#step:5:1001

**Comment by mrc0mmand** [comment]
This should be, hopefully, ready. The last commits are in a "wrong logical order", since the genius me did all the work on the latest commit and now switching them around introduces quite a lot of conflicts - hopefully it's not a big issue.

**Comment by evverx** [comment]
>  we should probably check the CI logs somehow for sanitizer errors

If I understand correctly I think `set -o pipefail` could have helped to catch that.

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
