### PR TITLE
rand: allow generating arbitrary D-Bus signatures

### PR DESCRIPTION
**Pull request by mrc0mmand**
Let's extend the random signature stuff a bit and allow generating
container types as well.

### CODE REVIEW

**Comment by mrc0mmand** [comment]
So, after some testing this appears to do the right thing, but I'd like to wait for Coveralls for the code coverage report to make sure all the new code is covered (they seem to be a bit backed up right now, so it might take a while https://status.coveralls.io/).

**Comment by mrc0mmand** [comment]
Looks like almost everything new is covered, so it should be good to go, @evverx PTAL!

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

I'll go ahead and merge it to let Coverity analyze it as well. I haven't tested it thoroughly but once it lands my scripts should be able to detect any issues if there are any.

**Comment by mrc0mmand** [comment]
> LGTM. Thanks!
> 
> I'll go ahead and merge it to let Coverity analyze it as well. I haven't tested it thoroughly but once it lands my scripts should be able to detect any issues if there are any.

D'oh, I guess I should've waited with the last commit :-)

**Comment by mrc0mmand** [comment]
Let me drop the last commit, since it needs further work, so the rest can be merged.

**Comment by evverx** [comment]
FWIW GitHub prevented me from merging this PR because it changed (even without any branch protection rules) so now I'm a bit more confident in GitHub overall :-) I'll wait for Packit to finish and merge it once it's green.

**Comment by evverx** [comment]
@mrc0mmand on an unrelated note, `v2.1` appears to have been released (yay!) but https://github.com/dbus-fuzzer/dfuzzer/blob/master/meson.build#L2 hasn't been changed accordingly so `--version` still shows `2.0`

**Comment by mrc0mmand** [comment]
Fixed in https://github.com/dbus-fuzzer/dfuzzer/commit/a765fece2c09e98fe6e9d26fd17eb455ce2eb542. Thanks for catching this, hopefully I won't forget to do it next time :-)

**Pull request merged**
