### PR TITLE
fuzz: generate an empty array on the first iteration

### PR DESCRIPTION
**Pull request by mrc0mmand**
if the signature contains an array.

### CODE REVIEW

**Comment by evverx** [comment]
It should make it easier to catch issues like https://github.com/systemd/systemd/issues/20933 I think.

I'm not sure where the coveralls comment came from. I suspect it has something to do with moving the repository to the organization.

**Comment by mrc0mmand** [comment]
> It should make it easier to catch issues like [systemd/systemd#20933](https://github.com/systemd/systemd/issues/20933) I think.

Yeah, I was inspired by your comment in https://github.com/dbus-fuzzer/dfuzzer/issues/81#issuecomment-1126913783. But it's just a low hanging fruit, having a dictionary support is still the end goal (which I'd like to have as soon as possible).

> 
> I'm not sure where the coveralls comment came from. I suspect it has something to do with moving the repository to the organization.

I'm not sure why they popped up just now, but disabling them is simple as just un-ticking a checkbox in the Coveralls settings (which I've just done), so that should hopefully solved it.

**Comment by evverx** [comment]
> disabling them is simple as just un-ticking a checkbox in the Coveralls settings

It's simple when you have access to those settings :-)

**Comment by mrc0mmand** [comment]
> > disabling them is simple as just un-ticking a checkbox in the Coveralls settings
> 
> It's simple when you have access to those settings :-)

Ah, I see, I wasn't sure what determines the access to Coveralls settings, but since it appears to be the GH ACL I've made you an owner as well, as you're responsible for most of the current CIs anyway :-)

**Comment by mrc0mmand** [comment]
Another 'ah', I was looking at my fork of this repo without realizing it, I can't access the settings for `dbus-fuzzer/dfuzzer` as well, I guess it needs an app to be installed to the organization?

**Comment by evverx** [comment]
I think it should be fixed now. Coveralls just didn't have access to the repository.

**Review by evverx — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
